### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by Xeoth** [MinecraftMemes-Mods/ApplicantVoting#1]
- [ ] Split applicant.tsx into components
- [ ] Login with Reddit
- [ ] Backend
- [ ] Find a host for this
